//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.reportsystem.model;


import akatsuki.reportsystem.model.documents.*;
import akatsuki.reportsystem.model.types.TPodnosilacInteresovanja;
import akatsuki.reportsystem.model.types.TPodnosilacZahteva;
import akatsuki.reportsystem.model.types.TPrimalac;
import akatsuki.reportsystem.model.types.TTipVakcine;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the io.codejournal.maven.xsd2java package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.codejournal.maven.xsd2java
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalniSertifikat }
     */
    public DigitalniSertifikat createDigitalniSertifikat() {
        return new DigitalniSertifikat();
    }

    /**
     * Create an instance of {@link Interesovanje }
     */
    public Interesovanje createInteresovanje() {
        return new Interesovanje();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji }
     */
    public IzvestajOImunizaciji createIzvestajOImunizaciji() {
        return new IzvestajOImunizaciji();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji }
     */
    public PotvrdaOVakcinaciji createPotvrdaOVakcinaciji() {
        return new PotvrdaOVakcinaciji();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju }
     */
    public SaglasnostZaImunizaciju createSaglasnostZaImunizaciju() {
        return new SaglasnostZaImunizaciju();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.EvidencijaOVakcinaciji }
     */
    public SaglasnostZaImunizaciju.EvidencijaOVakcinaciji createSaglasnostZaImunizacijuEvidencijaOVakcinaciji() {
        return new SaglasnostZaImunizaciju.EvidencijaOVakcinaciji();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine }
     */
    public SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine createSaglasnostZaImunizacijuEvidencijaOVakcinacijiVakcine() {
        return new SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent }
     */
    public SaglasnostZaImunizaciju.Pacijent createSaglasnostZaImunizacijuPacijent() {
        return new SaglasnostZaImunizaciju.Pacijent();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.SocijalnaZastita }
     */
    public SaglasnostZaImunizaciju.Pacijent.SocijalnaZastita createSaglasnostZaImunizacijuPacijentSocijalnaZastita() {
        return new SaglasnostZaImunizaciju.Pacijent.SocijalnaZastita();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.Prebivaliste }
     */
    public SaglasnostZaImunizaciju.Pacijent.Prebivaliste createSaglasnostZaImunizacijuPacijentPrebivaliste() {
        return new SaglasnostZaImunizaciju.Pacijent.Prebivaliste();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo }
     */
    public SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo createSaglasnostZaImunizacijuPacijentDrzavljanstvo() {
        return new SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.PrimljeneVakcine }
     */
    public PotvrdaOVakcinaciji.PrimljeneVakcine createPotvrdaOVakcinacijiPrimljeneVakcine() {
        return new PotvrdaOVakcinaciji.PrimljeneVakcine();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.DozeVakcina }
     */
    public IzvestajOImunizaciji.DozeVakcina createIzvestajOImunizacijiDozeVakcina() {
        return new IzvestajOImunizaciji.DozeVakcina();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.DozeVakcina.RaspodelaPoProizvodjacima }
     */
    public IzvestajOImunizaciji.DozeVakcina.RaspodelaPoProizvodjacima createIzvestajOImunizacijiDozeVakcinaRaspodelaPoProizvodjacima() {
        return new IzvestajOImunizaciji.DozeVakcina.RaspodelaPoProizvodjacima();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.DozeVakcina.RaspodelaPoDozama }
     */
    public IzvestajOImunizaciji.DozeVakcina.RaspodelaPoDozama createIzvestajOImunizacijiDozeVakcinaRaspodelaPoDozama() {
        return new IzvestajOImunizaciji.DozeVakcina.RaspodelaPoDozama();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.Dokumenti }
     */
    public IzvestajOImunizaciji.Dokumenti createIzvestajOImunizacijiDokumenti() {
        return new IzvestajOImunizaciji.Dokumenti();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Testovi }
     */
    public DigitalniSertifikat.Testovi createDigitalniSertifikatTestovi() {
        return new DigitalniSertifikat.Testovi();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Vakcinacija }
     */
    public DigitalniSertifikat.Vakcinacija createDigitalniSertifikatVakcinacija() {
        return new DigitalniSertifikat.Vakcinacija();
    }

    /**
     * Create an instance of {@link TPodnosilacZahteva }
     */
    public TPodnosilacZahteva createTPodnosilacZahteva() {
        return new TPodnosilacZahteva();
    }

    /**
     * Create an instance of {@link TPodnosilacInteresovanja }
     */
    public TPodnosilacInteresovanja createTPodnosilacInteresovanja() {
        return new TPodnosilacInteresovanja();
    }

    /**
     * Create an instance of {@link TPrimalac }
     */
    public TPrimalac createTPrimalac() {
        return new TPrimalac();
    }

    /**
     * Create an instance of {@link TTipVakcine }
     */
    public TTipVakcine createTTipVakcine() {
        return new TTipVakcine();
    }

    /**
     * Create an instance of {@link Interesovanje.Vakcine }
     */
    public Interesovanje.Vakcine createInteresovanjeVakcine() {
        return new Interesovanje.Vakcine();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.Period }
     */
    public IzvestajOImunizaciji.Period createIzvestajOImunizacijiPeriod() {
        return new IzvestajOImunizaciji.Period();
    }

    /**
     * Create an instance of {@link ZahtevZaSertifikat }
     */
    public ZahtevZaSertifikat createZahtevZaSertifikat() {
        return new ZahtevZaSertifikat();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Lekar }
     */
    public SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Lekar createSaglasnostZaImunizacijuEvidencijaOVakcinacijiLekar() {
        return new SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Lekar();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine.Vakcina }
     */
    public SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine.Vakcina createSaglasnostZaImunizacijuEvidencijaOVakcinacijiVakcineVakcina() {
        return new SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine.Vakcina();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine.Kontraindikacije }
     */
    public SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine.Kontraindikacije createSaglasnostZaImunizacijuEvidencijaOVakcinacijiVakcineKontraindikacije() {
        return new SaglasnostZaImunizaciju.EvidencijaOVakcinaciji.Vakcine.Kontraindikacije();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.Rodjenje }
     */
    public SaglasnostZaImunizaciju.Pacijent.Rodjenje createSaglasnostZaImunizacijuPacijentRodjenje() {
        return new SaglasnostZaImunizaciju.Pacijent.Rodjenje();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.IzjavaSaglasnosti }
     */
    public SaglasnostZaImunizaciju.Pacijent.IzjavaSaglasnosti createSaglasnostZaImunizacijuPacijentIzjavaSaglasnosti() {
        return new SaglasnostZaImunizaciju.Pacijent.IzjavaSaglasnosti();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.SocijalnaZastita.Sediste }
     */
    public SaglasnostZaImunizaciju.Pacijent.SocijalnaZastita.Sediste createSaglasnostZaImunizacijuPacijentSocijalnaZastitaSediste() {
        return new SaglasnostZaImunizaciju.Pacijent.SocijalnaZastita.Sediste();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.Prebivaliste.Adresa }
     */
    public SaglasnostZaImunizaciju.Pacijent.Prebivaliste.Adresa createSaglasnostZaImunizacijuPacijentPrebivalisteAdresa() {
        return new SaglasnostZaImunizaciju.Pacijent.Prebivaliste.Adresa();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo.Srpsko }
     */
    public SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo.Srpsko createSaglasnostZaImunizacijuPacijentDrzavljanstvoSrpsko() {
        return new SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo.Srpsko();
    }

    /**
     * Create an instance of {@link SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo.Strano }
     */
    public SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo.Strano createSaglasnostZaImunizacijuPacijentDrzavljanstvoStrano() {
        return new SaglasnostZaImunizaciju.Pacijent.Drzavljanstvo.Strano();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.PrimljeneVakcine.Doza }
     */
    public PotvrdaOVakcinaciji.PrimljeneVakcine.Doza createPotvrdaOVakcinacijiPrimljeneVakcineDoza() {
        return new PotvrdaOVakcinaciji.PrimljeneVakcine.Doza();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.DozeVakcina.RaspodelaPoProizvodjacima.Proizvodjac }
     */
    public IzvestajOImunizaciji.DozeVakcina.RaspodelaPoProizvodjacima.Proizvodjac createIzvestajOImunizacijiDozeVakcinaRaspodelaPoProizvodjacimaProizvodjac() {
        return new IzvestajOImunizaciji.DozeVakcina.RaspodelaPoProizvodjacima.Proizvodjac();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.DozeVakcina.RaspodelaPoDozama.Doza }
     */
    public IzvestajOImunizaciji.DozeVakcina.RaspodelaPoDozama.Doza createIzvestajOImunizacijiDozeVakcinaRaspodelaPoDozamaDoza() {
        return new IzvestajOImunizaciji.DozeVakcina.RaspodelaPoDozama.Doza();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.Dokumenti.ZeleniSertifikat }
     */
    public IzvestajOImunizaciji.Dokumenti.ZeleniSertifikat createIzvestajOImunizacijiDokumentiZeleniSertifikat() {
        return new IzvestajOImunizaciji.Dokumenti.ZeleniSertifikat();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Testovi.Test }
     */
    public DigitalniSertifikat.Testovi.Test createDigitalniSertifikatTestoviTest() {
        return new DigitalniSertifikat.Testovi.Test();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Vakcinacija.Doza }
     */
    public DigitalniSertifikat.Vakcinacija.Doza createDigitalniSertifikatVakcinacijaDoza() {
        return new DigitalniSertifikat.Vakcinacija.Doza();
    }

}
