//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.immunizationsystem.model.documents;

import akatsuki.immunizationsystem.model.types.TPodnosilacZahteva;
import akatsuki.immunizationsystem.model.types.TTipVakcine;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="primalac" type="{http://www.akatsuki.org/tipovi}TPodnosilacZahteva"/&gt;
 *         &lt;element name="vakcinacija"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="2"&gt;
 *                   &lt;element name="doza"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="tip" type="{http://www.akatsuki.org/tipovi}TTipVakcine"/&gt;
 *                             &lt;element name="proizvodjac_i_serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="testovi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="3" minOccurs="3"&gt;
 *                   &lt;element name="test"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="datum_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                             &lt;element name="datum_izdavanja_rezultata" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                             &lt;element name="rezultat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum_i_vreme_izdavanja" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="broj_sertifikata" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "primalac",
        "vakcinacija",
        "testovi"
})
@XmlRootElement(name = "digitalni_sertifikat", namespace = "http://www.akatsuki.org/digitalni_sertifikat")
public class DigitalniSertifikat {

    @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
    protected TPodnosilacZahteva primalac;
    @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
    protected Vakcinacija vakcinacija;
    @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
    protected Testovi testovi;
    @XmlAttribute(name = "datum_i_vreme_izdavanja", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumIVremeIzdavanja;
    @XmlAttribute(name = "broj_sertifikata", required = true)
    protected String brojSertifikata;

    /**
     * Gets the value of the primalac property.
     *
     * @return possible object is
     * {@link TPodnosilacZahteva }
     */
    public TPodnosilacZahteva getPrimalac() {
        return primalac;
    }

    /**
     * Sets the value of the primalac property.
     *
     * @param value allowed object is
     *              {@link TPodnosilacZahteva }
     */
    public void setPrimalac(TPodnosilacZahteva value) {
        this.primalac = value;
    }

    /**
     * Gets the value of the vakcinacija property.
     *
     * @return possible object is
     * {@link Vakcinacija }
     */
    public Vakcinacija getVakcinacija() {
        return vakcinacija;
    }

    /**
     * Sets the value of the vakcinacija property.
     *
     * @param value allowed object is
     *              {@link Vakcinacija }
     */
    public void setVakcinacija(Vakcinacija value) {
        this.vakcinacija = value;
    }

    /**
     * Gets the value of the testovi property.
     *
     * @return possible object is
     * {@link Testovi }
     */
    public Testovi getTestovi() {
        return testovi;
    }

    /**
     * Sets the value of the testovi property.
     *
     * @param value allowed object is
     *              {@link Testovi }
     */
    public void setTestovi(Testovi value) {
        this.testovi = value;
    }

    /**
     * Gets the value of the datumIVremeIzdavanja property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDatumIVremeIzdavanja() {
        return datumIVremeIzdavanja;
    }

    /**
     * Sets the value of the datumIVremeIzdavanja property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDatumIVremeIzdavanja(XMLGregorianCalendar value) {
        this.datumIVremeIzdavanja = value;
    }

    /**
     * Gets the value of the brojSertifikata property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrojSertifikata() {
        return brojSertifikata;
    }

    /**
     * Sets the value of the brojSertifikata property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrojSertifikata(String value) {
        this.brojSertifikata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="3" minOccurs="3"&gt;
     *         &lt;element name="test"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="datum_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *                   &lt;element name="datum_izdavanja_rezultata" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *                   &lt;element name="rezultat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "test"
    })
    public static class Testovi {

        @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
        protected List<Test> test;

        /**
         * Gets the value of the test property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the test property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTest().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Test }
         */
        public List<Test> getTest() {
            if (test == null) {
                test = new ArrayList<Test>();
            }
            return this.test;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="datum_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
         *         &lt;element name="datum_izdavanja_rezultata" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
         *         &lt;element name="rezultat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "vrstaUzorka",
                "proizvodjac",
                "datumUzorkovanja",
                "datumIzdavanjaRezultata",
                "rezultat",
                "laboratorija"
        })
        public static class Test {

            @XmlElement(name = "vrsta_uzorka", namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected String vrstaUzorka;
            @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected String proizvodjac;
            @XmlElement(name = "datum_uzorkovanja", namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar datumUzorkovanja;
            @XmlElement(name = "datum_izdavanja_rezultata", namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar datumIzdavanjaRezultata;
            @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected String rezultat;
            @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected String laboratorija;

            /**
             * Gets the value of the vrstaUzorka property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getVrstaUzorka() {
                return vrstaUzorka;
            }

            /**
             * Sets the value of the vrstaUzorka property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setVrstaUzorka(String value) {
                this.vrstaUzorka = value;
            }

            /**
             * Gets the value of the proizvodjac property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getProizvodjac() {
                return proizvodjac;
            }

            /**
             * Sets the value of the proizvodjac property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setProizvodjac(String value) {
                this.proizvodjac = value;
            }

            /**
             * Gets the value of the datumUzorkovanja property.
             *
             * @return possible object is
             * {@link XMLGregorianCalendar }
             */
            public XMLGregorianCalendar getDatumUzorkovanja() {
                return datumUzorkovanja;
            }

            /**
             * Sets the value of the datumUzorkovanja property.
             *
             * @param value allowed object is
             *              {@link XMLGregorianCalendar }
             */
            public void setDatumUzorkovanja(XMLGregorianCalendar value) {
                this.datumUzorkovanja = value;
            }

            /**
             * Gets the value of the datumIzdavanjaRezultata property.
             *
             * @return possible object is
             * {@link XMLGregorianCalendar }
             */
            public XMLGregorianCalendar getDatumIzdavanjaRezultata() {
                return datumIzdavanjaRezultata;
            }

            /**
             * Sets the value of the datumIzdavanjaRezultata property.
             *
             * @param value allowed object is
             *              {@link XMLGregorianCalendar }
             */
            public void setDatumIzdavanjaRezultata(XMLGregorianCalendar value) {
                this.datumIzdavanjaRezultata = value;
            }

            /**
             * Gets the value of the rezultat property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getRezultat() {
                return rezultat;
            }

            /**
             * Sets the value of the rezultat property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setRezultat(String value) {
                this.rezultat = value;
            }

            /**
             * Gets the value of the laboratorija property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getLaboratorija() {
                return laboratorija;
            }

            /**
             * Sets the value of the laboratorija property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setLaboratorija(String value) {
                this.laboratorija = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="2"&gt;
     *         &lt;element name="doza"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="tip" type="{http://www.akatsuki.org/tipovi}TTipVakcine"/&gt;
     *                   &lt;element name="proizvodjac_i_serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "doza"
    })
    public static class Vakcinacija {

        @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
        protected List<Doza> doza;

        /**
         * Gets the value of the doza property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doza property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDoza().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Doza }
         */
        public List<Doza> getDoza() {
            if (doza == null) {
                doza = new ArrayList<Doza>();
            }
            return this.doza;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="tip" type="{http://www.akatsuki.org/tipovi}TTipVakcine"/&gt;
         *         &lt;element name="proizvodjac_i_serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "tip",
                "proizvodjacISerija",
                "datum",
                "zdravstvenaUstanova"
        })
        public static class Doza {

            @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected TTipVakcine tip;
            @XmlElement(name = "proizvodjac_i_serija", namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected String proizvodjacISerija;
            @XmlElement(namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datum;
            @XmlElement(name = "zdravstvena_ustanova", namespace = "http://www.akatsuki.org/digitalni_sertifikat", required = true)
            protected String zdravstvenaUstanova;
            @XmlAttribute(name = "broj")
            protected Integer broj;

            /**
             * Gets the value of the tip property.
             *
             * @return possible object is
             * {@link TTipVakcine }
             */
            public TTipVakcine getTip() {
                return tip;
            }

            /**
             * Sets the value of the tip property.
             *
             * @param value allowed object is
             *              {@link TTipVakcine }
             */
            public void setTip(TTipVakcine value) {
                this.tip = value;
            }

            /**
             * Gets the value of the proizvodjacISerija property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getProizvodjacISerija() {
                return proizvodjacISerija;
            }

            /**
             * Sets the value of the proizvodjacISerija property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setProizvodjacISerija(String value) {
                this.proizvodjacISerija = value;
            }

            /**
             * Gets the value of the datum property.
             *
             * @return possible object is
             * {@link XMLGregorianCalendar }
             */
            public XMLGregorianCalendar getDatum() {
                return datum;
            }

            /**
             * Sets the value of the datum property.
             *
             * @param value allowed object is
             *              {@link XMLGregorianCalendar }
             */
            public void setDatum(XMLGregorianCalendar value) {
                this.datum = value;
            }

            /**
             * Gets the value of the zdravstvenaUstanova property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getZdravstvenaUstanova() {
                return zdravstvenaUstanova;
            }

            /**
             * Sets the value of the zdravstvenaUstanova property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setZdravstvenaUstanova(String value) {
                this.zdravstvenaUstanova = value;
            }

            /**
             * Gets the value of the broj property.
             *
             * @return possible object is
             * {@link Integer }
             */
            public Integer getBroj() {
                return broj;
            }

            /**
             * Sets the value of the broj property.
             *
             * @param value allowed object is
             *              {@link Integer }
             */
            public void setBroj(Integer value) {
                this.broj = value;
            }

        }

    }

}
