//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.immunizationsystem.model.documents;

import akatsuki.immunizationsystem.model.types.TDrzavljanstvo;
import akatsuki.immunizationsystem.model.types.TPodnosilacInteresovanja;
import akatsuki.immunizationsystem.model.types.TTipVakcine;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="drzavljanstvo" type="{http://www.akatsuki.org/interesovanje}TDrzavljanstvo"/&gt;
 *         &lt;element name="podnosilac" type="{http://www.akatsuki.org/tipovi}TPodnosilacInteresovanja"/&gt;
 *         &lt;element name="vakcine"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="vakcina" type="{http://www.akatsuki.org/tipovi}TTipVakcine" maxOccurs="6"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dobrovoljni_davalac_krvi" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "drzavljanstvo",
        "podnosilac",
        "vakcine",
        "dobrovoljniDavalacKrvi"
})
@XmlRootElement(name = "interesovanje", namespace = "http://www.akatsuki.org/interesovanje")
public class Interesovanje {

    @XmlElement(namespace = "http://www.akatsuki.org/interesovanje", required = true)
    @XmlSchemaType(name = "string")
    protected TDrzavljanstvo drzavljanstvo;
    @XmlElement(namespace = "http://www.akatsuki.org/interesovanje", required = true)
    protected TPodnosilacInteresovanja podnosilac;
    @XmlElement(namespace = "http://www.akatsuki.org/interesovanje", required = true)
    protected Vakcine vakcine;
    @XmlElement(name = "dobrovoljni_davalac_krvi", namespace = "http://www.akatsuki.org/interesovanje")
    protected boolean dobrovoljniDavalacKrvi;

    /**
     * Gets the value of the drzavljanstvo property.
     *
     * @return possible object is
     * {@link TDrzavljanstvo }
     */
    public TDrzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     *
     * @param value allowed object is
     *              {@link TDrzavljanstvo }
     */
    public void setDrzavljanstvo(TDrzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the podnosilac property.
     *
     * @return possible object is
     * {@link TPodnosilacInteresovanja }
     */
    public TPodnosilacInteresovanja getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     *
     * @param value allowed object is
     *              {@link TPodnosilacInteresovanja }
     */
    public void setPodnosilac(TPodnosilacInteresovanja value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the vakcine property.
     *
     * @return possible object is
     * {@link Vakcine }
     */
    public Vakcine getVakcine() {
        return vakcine;
    }

    /**
     * Sets the value of the vakcine property.
     *
     * @param value allowed object is
     *              {@link Vakcine }
     */
    public void setVakcine(Vakcine value) {
        this.vakcine = value;
    }

    /**
     * Gets the value of the dobrovoljniDavalacKrvi property.
     */
    public boolean isDobrovoljniDavalacKrvi() {
        return dobrovoljniDavalacKrvi;
    }

    /**
     * Sets the value of the dobrovoljniDavalacKrvi property.
     */
    public void setDobrovoljniDavalacKrvi(boolean value) {
        this.dobrovoljniDavalacKrvi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="vakcina" type="{http://www.akatsuki.org/tipovi}TTipVakcine" maxOccurs="6"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "vakcina"
    })
    public static class Vakcine {

        @XmlElement(namespace = "http://www.akatsuki.org/interesovanje", required = true)
        protected List<TTipVakcine> vakcina;

        /**
         * Gets the value of the vakcina property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vakcina property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVakcina().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTipVakcine }
         */
        public List<TTipVakcine> getVakcina() {
            if (vakcina == null) {
                vakcina = new ArrayList<TTipVakcine>();
            }
            return this.vakcina;
        }

    }

}
