//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.immunizationsystem.model.documents;

import akatsuki.immunizationsystem.model.types.TNazivVakcine;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="period"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="od" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="do" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dokumenti"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="interesovanje_za_imunizaciju"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="0"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="zeleni_sertifikat"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="primljeno"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                   &lt;minInclusive value="0"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="izdato"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                   &lt;minInclusive value="0"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="doze_vakcina"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="raspodela_po_dozama"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="doza" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="broj"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                           &lt;minInclusive value="1"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                     &lt;attribute name="kolicina"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                           &lt;minInclusive value="1"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="raspodela_po_proizvodjacima"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="proizvodjac" maxOccurs="5" minOccurs="5"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine" /&gt;
 *                                     &lt;attribute name="kolicina"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                           &lt;minInclusive value="0"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="izdato"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                       &lt;minInclusive value="1"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "period",
        "dokumenti",
        "dozeVakcina"
})
@XmlRootElement(name = "izvestaj_o_imunizaciji", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji")
public class IzvestajOImunizaciji {

    @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
    protected Period period;
    @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
    protected Dokumenti dokumenti;
    @XmlElement(name = "doze_vakcina", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
    protected DozeVakcina dozeVakcina;
    @XmlAttribute(name = "datum_izdavanja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;

    /**
     * Gets the value of the period property.
     *
     * @return possible object is
     * {@link Period }
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     *
     * @param value allowed object is
     *              {@link Period }
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the dokumenti property.
     *
     * @return possible object is
     * {@link Dokumenti }
     */
    public Dokumenti getDokumenti() {
        return dokumenti;
    }

    /**
     * Sets the value of the dokumenti property.
     *
     * @param value allowed object is
     *              {@link Dokumenti }
     */
    public void setDokumenti(Dokumenti value) {
        this.dokumenti = value;
    }

    /**
     * Gets the value of the dozeVakcina property.
     *
     * @return possible object is
     * {@link DozeVakcina }
     */
    public DozeVakcina getDozeVakcina() {
        return dozeVakcina;
    }

    /**
     * Sets the value of the dozeVakcina property.
     *
     * @param value allowed object is
     *              {@link DozeVakcina }
     */
    public void setDozeVakcina(DozeVakcina value) {
        this.dozeVakcina = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="interesovanje_za_imunizaciju"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="0"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="zeleni_sertifikat"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="primljeno"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                         &lt;minInclusive value="0"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="izdato"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                         &lt;minInclusive value="0"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "interesovanjeZaImunizaciju",
            "zeleniSertifikat"
    })
    public static class Dokumenti {

        @XmlElement(name = "interesovanje_za_imunizaciju", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji")
        protected int interesovanjeZaImunizaciju;
        @XmlElement(name = "zeleni_sertifikat", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
        protected ZeleniSertifikat zeleniSertifikat;

        /**
         * Gets the value of the interesovanjeZaImunizaciju property.
         */
        public int getInteresovanjeZaImunizaciju() {
            return interesovanjeZaImunizaciju;
        }

        /**
         * Sets the value of the interesovanjeZaImunizaciju property.
         */
        public void setInteresovanjeZaImunizaciju(int value) {
            this.interesovanjeZaImunizaciju = value;
        }

        /**
         * Gets the value of the zeleniSertifikat property.
         *
         * @return possible object is
         * {@link ZeleniSertifikat }
         */
        public ZeleniSertifikat getZeleniSertifikat() {
            return zeleniSertifikat;
        }

        /**
         * Sets the value of the zeleniSertifikat property.
         *
         * @param value allowed object is
         *              {@link ZeleniSertifikat }
         */
        public void setZeleniSertifikat(ZeleniSertifikat value) {
            this.zeleniSertifikat = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="primljeno"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *               &lt;minInclusive value="0"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="izdato"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *               &lt;minInclusive value="0"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "primljeno",
                "izdato"
        })
        public static class ZeleniSertifikat {

            @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji")
            protected int primljeno;
            @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji")
            protected int izdato;

            /**
             * Gets the value of the primljeno property.
             */
            public int getPrimljeno() {
                return primljeno;
            }

            /**
             * Sets the value of the primljeno property.
             */
            public void setPrimljeno(int value) {
                this.primljeno = value;
            }

            /**
             * Gets the value of the izdato property.
             */
            public int getIzdato() {
                return izdato;
            }

            /**
             * Sets the value of the izdato property.
             */
            public void setIzdato(int value) {
                this.izdato = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="raspodela_po_dozama"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="doza" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="broj"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                                 &lt;minInclusive value="1"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                           &lt;attribute name="kolicina"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                                 &lt;minInclusive value="1"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="raspodela_po_proizvodjacima"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="proizvodjac" maxOccurs="5" minOccurs="5"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine" /&gt;
     *                           &lt;attribute name="kolicina"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                                 &lt;minInclusive value="0"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="izdato"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *             &lt;minInclusive value="1"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "raspodelaPoDozama",
            "raspodelaPoProizvodjacima"
    })
    public static class DozeVakcina {

        @XmlElement(name = "raspodela_po_dozama", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
        protected RaspodelaPoDozama raspodelaPoDozama;
        @XmlElement(name = "raspodela_po_proizvodjacima", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
        protected RaspodelaPoProizvodjacima raspodelaPoProizvodjacima;
        @XmlAttribute(name = "izdato")
        protected Integer izdato;

        /**
         * Gets the value of the raspodelaPoDozama property.
         *
         * @return possible object is
         * {@link RaspodelaPoDozama }
         */
        public RaspodelaPoDozama getRaspodelaPoDozama() {
            return raspodelaPoDozama;
        }

        /**
         * Sets the value of the raspodelaPoDozama property.
         *
         * @param value allowed object is
         *              {@link RaspodelaPoDozama }
         */
        public void setRaspodelaPoDozama(RaspodelaPoDozama value) {
            this.raspodelaPoDozama = value;
        }

        /**
         * Gets the value of the raspodelaPoProizvodjacima property.
         *
         * @return possible object is
         * {@link RaspodelaPoProizvodjacima }
         */
        public RaspodelaPoProizvodjacima getRaspodelaPoProizvodjacima() {
            return raspodelaPoProizvodjacima;
        }

        /**
         * Sets the value of the raspodelaPoProizvodjacima property.
         *
         * @param value allowed object is
         *              {@link RaspodelaPoProizvodjacima }
         */
        public void setRaspodelaPoProizvodjacima(RaspodelaPoProizvodjacima value) {
            this.raspodelaPoProizvodjacima = value;
        }

        /**
         * Gets the value of the izdato property.
         *
         * @return possible object is
         * {@link Integer }
         */
        public Integer getIzdato() {
            return izdato;
        }

        /**
         * Sets the value of the izdato property.
         *
         * @param value allowed object is
         *              {@link Integer }
         */
        public void setIzdato(Integer value) {
            this.izdato = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="doza" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="broj"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *                       &lt;minInclusive value="1"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *                 &lt;attribute name="kolicina"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *                       &lt;minInclusive value="1"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "doza"
        })
        public static class RaspodelaPoDozama {

            @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji")
            protected List<Doza> doza;

            /**
             * Gets the value of the doza property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the doza property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDoza().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Doza }
             */
            public List<Doza> getDoza() {
                if (doza == null) {
                    doza = new ArrayList<Doza>();
                }
                return this.doza;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="broj"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
             *             &lt;minInclusive value="1"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *       &lt;attribute name="kolicina"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
             *             &lt;minInclusive value="1"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Doza {

                @XmlAttribute(name = "broj")
                protected Integer broj;
                @XmlAttribute(name = "kolicina")
                protected Integer kolicina;

                /**
                 * Gets the value of the broj property.
                 *
                 * @return possible object is
                 * {@link Integer }
                 */
                public Integer getBroj() {
                    return broj;
                }

                /**
                 * Sets the value of the broj property.
                 *
                 * @param value allowed object is
                 *              {@link Integer }
                 */
                public void setBroj(Integer value) {
                    this.broj = value;
                }

                /**
                 * Gets the value of the kolicina property.
                 *
                 * @return possible object is
                 * {@link Integer }
                 */
                public Integer getKolicina() {
                    return kolicina;
                }

                /**
                 * Sets the value of the kolicina property.
                 *
                 * @param value allowed object is
                 *              {@link Integer }
                 */
                public void setKolicina(Integer value) {
                    this.kolicina = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="proizvodjac" maxOccurs="5" minOccurs="5"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine" /&gt;
         *                 &lt;attribute name="kolicina"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *                       &lt;minInclusive value="0"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "proizvodjac"
        })
        public static class RaspodelaPoProizvodjacima {

            @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
            protected List<Proizvodjac> proizvodjac;

            /**
             * Gets the value of the proizvodjac property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the proizvodjac property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProizvodjac().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Proizvodjac }
             */
            public List<Proizvodjac> getProizvodjac() {
                if (proizvodjac == null) {
                    proizvodjac = new ArrayList<Proizvodjac>();
                }
                return this.proizvodjac;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine" /&gt;
             *       &lt;attribute name="kolicina"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
             *             &lt;minInclusive value="0"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Proizvodjac {

                @XmlAttribute(name = "naziv")
                protected TNazivVakcine naziv;
                @XmlAttribute(name = "kolicina")
                protected Integer kolicina;

                /**
                 * Gets the value of the naziv property.
                 *
                 * @return possible object is
                 * {@link TNazivVakcine }
                 */
                public TNazivVakcine getNaziv() {
                    return naziv;
                }

                /**
                 * Sets the value of the naziv property.
                 *
                 * @param value allowed object is
                 *              {@link TNazivVakcine }
                 */
                public void setNaziv(TNazivVakcine value) {
                    this.naziv = value;
                }

                /**
                 * Gets the value of the kolicina property.
                 *
                 * @return possible object is
                 * {@link Integer }
                 */
                public Integer getKolicina() {
                    return kolicina;
                }

                /**
                 * Sets the value of the kolicina property.
                 *
                 * @param value allowed object is
                 *              {@link Integer }
                 */
                public void setKolicina(Integer value) {
                    this.kolicina = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="od" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="do" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "od",
            "_do"
    })
    public static class Period {

        @XmlElement(namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar od;
        @XmlElement(name = "do", namespace = "http://www.akatsuki.org/izvestaj_o_imunizaciji", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar _do;

        /**
         * Gets the value of the od property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getOd() {
            return od;
        }

        /**
         * Sets the value of the od property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setOd(XMLGregorianCalendar value) {
            this.od = value;
        }

        /**
         * Gets the value of the do property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDo() {
            return _do;
        }

        /**
         * Sets the value of the do property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setDo(XMLGregorianCalendar value) {
            this._do = value;
        }

    }

}
