//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.immunizationsystem.model.documents;

import akatsuki.immunizationsystem.model.types.TNazivVakcineIzvrseneVakcinacije;
import akatsuki.immunizationsystem.model.types.TPrimalac;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="primalac" type="{http://www.akatsuki.org/tipovi}TPrimalac"/&gt;
 *         &lt;element name="primljene_vakcine"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="doza" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="datum_davanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="naziv_vakcine" type="{http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji}TNazivVakcineIzvrseneVakcinacije"/&gt;
 *         &lt;element name="qr_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primalac",
    "primljeneVakcine",
    "zdravstvenaUstanova",
    "nazivVakcine",
    "qrCode"
})
@XmlRootElement(name = "potvrda_o_vakcinaciji", namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji")
public class PotvrdaOVakcinaciji {

    @XmlElement(namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
    protected TPrimalac primalac;
    @XmlElement(name = "primljene_vakcine", namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
    protected PrimljeneVakcine primljeneVakcine;
    @XmlElement(name = "zdravstvena_ustanova", namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
    protected String zdravstvenaUstanova;
    @XmlElement(name = "naziv_vakcine", namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
    @XmlSchemaType(name = "string")
    protected TNazivVakcineIzvrseneVakcinacije nazivVakcine;
    @XmlElement(name = "qr_code", namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
    protected String qrCode;
    @XmlAttribute(name = "datum_izdavanja")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;

    /**
     * Gets the value of the primalac property.
     * 
     * @return
     *     possible object is
     *     {@link TPrimalac }
     *     
     */
    public TPrimalac getPrimalac() {
        return primalac;
    }

    /**
     * Sets the value of the primalac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrimalac }
     *     
     */
    public void setPrimalac(TPrimalac value) {
        this.primalac = value;
    }

    /**
     * Gets the value of the primljeneVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link PrimljeneVakcine }
     *     
     */
    public PrimljeneVakcine getPrimljeneVakcine() {
        return primljeneVakcine;
    }

    /**
     * Sets the value of the primljeneVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimljeneVakcine }
     *     
     */
    public void setPrimljeneVakcine(PrimljeneVakcine value) {
        this.primljeneVakcine = value;
    }

    /**
     * Gets the value of the zdravstvenaUstanova property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZdravstvenaUstanova() {
        return zdravstvenaUstanova;
    }

    /**
     * Sets the value of the zdravstvenaUstanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZdravstvenaUstanova(String value) {
        this.zdravstvenaUstanova = value;
    }

    /**
     * Gets the value of the nazivVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link TNazivVakcineIzvrseneVakcinacije }
     *     
     */
    public TNazivVakcineIzvrseneVakcinacije getNazivVakcine() {
        return nazivVakcine;
    }

    /**
     * Sets the value of the nazivVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNazivVakcineIzvrseneVakcinacije }
     *     
     */
    public void setNazivVakcine(TNazivVakcineIzvrseneVakcinacije value) {
        this.nazivVakcine = value;
    }

    /**
     * Gets the value of the qrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * Sets the value of the qrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrCode(String value) {
        this.qrCode = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="doza" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="datum_davanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "doza"
    })
    public static class PrimljeneVakcine {

        @XmlElement(namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
        protected List<Doza> doza;

        /**
         * Gets the value of the doza property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doza property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDoza().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Doza }
         * 
         * 
         */
        public List<Doza> getDoza() {
            if (doza == null) {
                doza = new ArrayList<Doza>();
            }
            return this.doza;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="datum_davanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datumDavanja",
            "serija"
        })
        public static class Doza {

            @XmlElement(name = "datum_davanja", namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumDavanja;
            @XmlElement(namespace = "http://www.akatsuki.org/potvrda_o_izvrsenoj_vakcinaciji", required = true)
            protected String serija;
            @XmlAttribute(name = "broj")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger broj;

            /**
             * Gets the value of the datumDavanja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumDavanja() {
                return datumDavanja;
            }

            /**
             * Sets the value of the datumDavanja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumDavanja(XMLGregorianCalendar value) {
                this.datumDavanja = value;
            }

            /**
             * Gets the value of the serija property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerija() {
                return serija;
            }

            /**
             * Sets the value of the serija property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerija(String value) {
                this.serija = value;
            }

            /**
             * Gets the value of the broj property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBroj() {
                if (broj == null) {
                    return new BigInteger("1");
                } else {
                    return broj;
                }
            }

            /**
             * Sets the value of the broj property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBroj(BigInteger value) {
                this.broj = value;
            }

        }

    }

}
