//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.immunizationsystem.model.documents;

import akatsuki.immunizationsystem.model.types.TNazivVakcine;
import akatsuki.immunizationsystem.model.types.TPol;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pacijent"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="drzavljanstvo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="srpsko"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="jmbg" type="{http://www.akatsuki.org/tipovi}TJmbg"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="strano"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="broj_pasosa" type="{http://www.akatsuki.org/tipovi}TBrojPasosa"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="puno_ime"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="pol" type="{http://www.akatsuki.org/tipovi}TPol"/&gt;
 *                   &lt;element name="rodjenje"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="prebivaliste"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="adresa"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="mesto_stanovanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="fiksni_telefon" type="{http://www.akatsuki.org/tipovi}TFiksniTelefon"/&gt;
 *                   &lt;element name="mobilni_telefon" type="{http://www.akatsuki.org/tipovi}TTelefon"/&gt;
 *                   &lt;element name="imejl" type="{http://www.akatsuki.org/tipovi}TEmail"/&gt;
 *                   &lt;element name="radni_status"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="zaposlen"/&gt;
 *                         &lt;enumeration value="nezaposlen"/&gt;
 *                         &lt;enumeration value="penzioner"/&gt;
 *                         &lt;enumeration value="ucenik"/&gt;
 *                         &lt;enumeration value="student"/&gt;
 *                         &lt;enumeration value="dete"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="zanimanje"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="zdravstvena_zastita"/&gt;
 *                         &lt;enumeration value="socijalna_zastita"/&gt;
 *                         &lt;enumeration value="prosveta"/&gt;
 *                         &lt;enumeration value="mup"/&gt;
 *                         &lt;enumeration value="vojska_rs"/&gt;
 *                         &lt;enumeration value="drugo"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="socijalna_zastita"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="sediste"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="izjava_saglasnosti"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="saglasnost" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="naziv_leka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="datum_popunjavanja" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="evidencija_o_vakcinaciji"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="vakcinacijski_punkt" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="lekar"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="telefon" type="{http://www.akatsuki.org/tipovi}TFiksniTelefon"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="vakcine"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence maxOccurs="unbounded" minOccurs="2"&gt;
 *                               &lt;element name="vakcina"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine"/&gt;
 *                                         &lt;element name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                         &lt;element name="nacin_davanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                         &lt;element name="ekstremitet"&gt;
 *                                           &lt;simpleType&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                               &lt;enumeration value="LR"/&gt;
 *                                               &lt;enumeration value="DR"/&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/simpleType&gt;
 *                                         &lt;/element&gt;
 *                                         &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                         &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                         &lt;element name="nezeljena_reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;element name="kontraindikacije"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pacijent",
        "evidencijaOVakcinaciji"
})
@XmlRootElement(name = "saglasnost_za_imunizaciju", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju")
public class SaglasnostZaImunizaciju {

    @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
    protected Pacijent pacijent;
    @XmlElement(name = "evidencija_o_vakcinaciji", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
    protected EvidencijaOVakcinaciji evidencijaOVakcinaciji;

    /**
     * Gets the value of the pacijent property.
     *
     * @return possible object is
     * {@link Pacijent }
     */
    public Pacijent getPacijent() {
        return pacijent;
    }

    /**
     * Sets the value of the pacijent property.
     *
     * @param value allowed object is
     *              {@link Pacijent }
     */
    public void setPacijent(Pacijent value) {
        this.pacijent = value;
    }

    /**
     * Gets the value of the evidencijaOVakcinaciji property.
     *
     * @return possible object is
     * {@link EvidencijaOVakcinaciji }
     */
    public EvidencijaOVakcinaciji getEvidencijaOVakcinaciji() {
        return evidencijaOVakcinaciji;
    }

    /**
     * Sets the value of the evidencijaOVakcinaciji property.
     *
     * @param value allowed object is
     *              {@link EvidencijaOVakcinaciji }
     */
    public void setEvidencijaOVakcinaciji(EvidencijaOVakcinaciji value) {
        this.evidencijaOVakcinaciji = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="zdravstvena_ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="vakcinacijski_punkt" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="lekar"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="telefon" type="{http://www.akatsuki.org/tipovi}TFiksniTelefon"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="vakcine"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence maxOccurs="unbounded" minOccurs="2"&gt;
     *                     &lt;element name="vakcina"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine"/&gt;
     *                               &lt;element name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                               &lt;element name="nacin_davanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                               &lt;element name="ekstremitet"&gt;
     *                                 &lt;simpleType&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                     &lt;enumeration value="LR"/&gt;
     *                                     &lt;enumeration value="DR"/&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/simpleType&gt;
     *                               &lt;/element&gt;
     *                               &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                               &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                               &lt;element name="nezeljena_reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;element name="kontraindikacije"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                             &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "zdravstvenaUstanova",
            "vakcinacijskiPunkt",
            "lekar",
            "vakcine"
    })
    public static class EvidencijaOVakcinaciji {

        @XmlElement(name = "zdravstvena_ustanova", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected String zdravstvenaUstanova;
        @XmlElement(name = "vakcinacijski_punkt", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected BigInteger vakcinacijskiPunkt;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected Lekar lekar;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected Vakcine vakcine;

        /**
         * Gets the value of the zdravstvenaUstanova property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getZdravstvenaUstanova() {
            return zdravstvenaUstanova;
        }

        /**
         * Sets the value of the zdravstvenaUstanova property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setZdravstvenaUstanova(String value) {
            this.zdravstvenaUstanova = value;
        }

        /**
         * Gets the value of the vakcinacijskiPunkt property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getVakcinacijskiPunkt() {
            return vakcinacijskiPunkt;
        }

        /**
         * Sets the value of the vakcinacijskiPunkt property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setVakcinacijskiPunkt(BigInteger value) {
            this.vakcinacijskiPunkt = value;
        }

        /**
         * Gets the value of the lekar property.
         *
         * @return possible object is
         * {@link Lekar }
         */
        public Lekar getLekar() {
            return lekar;
        }

        /**
         * Sets the value of the lekar property.
         *
         * @param value allowed object is
         *              {@link Lekar }
         */
        public void setLekar(Lekar value) {
            this.lekar = value;
        }

        /**
         * Gets the value of the vakcine property.
         *
         * @return possible object is
         * {@link Vakcine }
         */
        public Vakcine getVakcine() {
            return vakcine;
        }

        /**
         * Sets the value of the vakcine property.
         *
         * @param value allowed object is
         *              {@link Vakcine }
         */
        public void setVakcine(Vakcine value) {
            this.vakcine = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="telefon" type="{http://www.akatsuki.org/tipovi}TFiksniTelefon"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "ime",
                "prezime",
                "telefon"
        })
        public static class Lekar {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String ime;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String prezime;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String telefon;

            /**
             * Gets the value of the ime property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the telefon property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getTelefon() {
                return telefon;
            }

            /**
             * Sets the value of the telefon property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setTelefon(String value) {
                this.telefon = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence maxOccurs="unbounded" minOccurs="2"&gt;
         *           &lt;element name="vakcina"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine"/&gt;
         *                     &lt;element name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                     &lt;element name="nacin_davanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                     &lt;element name="ekstremitet"&gt;
         *                       &lt;simpleType&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                           &lt;enumeration value="LR"/&gt;
         *                           &lt;enumeration value="DR"/&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/simpleType&gt;
         *                     &lt;/element&gt;
         *                     &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                     &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                     &lt;element name="nezeljena_reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *         &lt;/sequence&gt;
         *         &lt;element name="kontraindikacije"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                   &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="odluka_komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "vakcina",
                "kontraindikacije",
                "odlukaKomisije"
        })
        public static class Vakcine {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected List<Vakcina> vakcina;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected Kontraindikacije kontraindikacije;
            @XmlElement(name = "odluka_komisije", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju")
            protected boolean odlukaKomisije;

            /**
             * Gets the value of the vakcina property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the vakcina property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVakcina().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Vakcina }
             */
            public List<Vakcina> getVakcina() {
                if (vakcina == null) {
                    vakcina = new ArrayList<Vakcina>();
                }
                return this.vakcina;
            }

            /**
             * Gets the value of the kontraindikacije property.
             *
             * @return possible object is
             * {@link Kontraindikacije }
             */
            public Kontraindikacije getKontraindikacije() {
                return kontraindikacije;
            }

            /**
             * Sets the value of the kontraindikacije property.
             *
             * @param value allowed object is
             *              {@link Kontraindikacije }
             */
            public void setKontraindikacije(Kontraindikacije value) {
                this.kontraindikacije = value;
            }

            /**
             * Gets the value of the odlukaKomisije property.
             */
            public boolean isOdlukaKomisije() {
                return odlukaKomisije;
            }

            /**
             * Sets the value of the odlukaKomisije property.
             */
            public void setOdlukaKomisije(boolean value) {
                this.odlukaKomisije = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="datum_utvrdjivanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "datumUtvrdjivanja",
                    "dijagnoza"
            })
            public static class Kontraindikacije {

                @XmlElement(name = "datum_utvrdjivanja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar datumUtvrdjivanja;
                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String dijagnoza;

                /**
                 * Gets the value of the datumUtvrdjivanja property.
                 *
                 * @return possible object is
                 * {@link XMLGregorianCalendar }
                 */
                public XMLGregorianCalendar getDatumUtvrdjivanja() {
                    return datumUtvrdjivanja;
                }

                /**
                 * Sets the value of the datumUtvrdjivanja property.
                 *
                 * @param value allowed object is
                 *              {@link XMLGregorianCalendar }
                 */
                public void setDatumUtvrdjivanja(XMLGregorianCalendar value) {
                    this.datumUtvrdjivanja = value;
                }

                /**
                 * Gets the value of the dijagnoza property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getDijagnoza() {
                    return dijagnoza;
                }

                /**
                 * Sets the value of the dijagnoza property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setDijagnoza(String value) {
                    this.dijagnoza = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="naziv" type="{http://www.akatsuki.org/tipovi}TNazivVakcine"/&gt;
             *         &lt;element name="datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="nacin_davanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="ekstremitet"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *               &lt;enumeration value="LR"/&gt;
             *               &lt;enumeration value="DR"/&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="serija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="nezeljena_reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "naziv",
                    "datumIzdavanja",
                    "nacinDavanja",
                    "ekstremitet",
                    "serija",
                    "proizvodjac",
                    "nezeljenaReakcija"
            })
            public static class Vakcina {

                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                @XmlSchemaType(name = "string")
                protected TNazivVakcine naziv;
                @XmlElement(name = "datum_izdavanja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar datumIzdavanja;
                @XmlElement(name = "nacin_davanja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String nacinDavanja;
                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String ekstremitet;
                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String serija;
                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String proizvodjac;
                @XmlElement(name = "nezeljena_reakcija", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String nezeljenaReakcija;

                /**
                 * Gets the value of the naziv property.
                 *
                 * @return possible object is
                 * {@link TNazivVakcine }
                 */
                public TNazivVakcine getNaziv() {
                    return naziv;
                }

                /**
                 * Sets the value of the naziv property.
                 *
                 * @param value allowed object is
                 *              {@link TNazivVakcine }
                 */
                public void setNaziv(TNazivVakcine value) {
                    this.naziv = value;
                }

                /**
                 * Gets the value of the datumIzdavanja property.
                 *
                 * @return possible object is
                 * {@link XMLGregorianCalendar }
                 */
                public XMLGregorianCalendar getDatumIzdavanja() {
                    return datumIzdavanja;
                }

                /**
                 * Sets the value of the datumIzdavanja property.
                 *
                 * @param value allowed object is
                 *              {@link XMLGregorianCalendar }
                 */
                public void setDatumIzdavanja(XMLGregorianCalendar value) {
                    this.datumIzdavanja = value;
                }

                /**
                 * Gets the value of the nacinDavanja property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getNacinDavanja() {
                    return nacinDavanja;
                }

                /**
                 * Sets the value of the nacinDavanja property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setNacinDavanja(String value) {
                    this.nacinDavanja = value;
                }

                /**
                 * Gets the value of the ekstremitet property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getEkstremitet() {
                    return ekstremitet;
                }

                /**
                 * Sets the value of the ekstremitet property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setEkstremitet(String value) {
                    this.ekstremitet = value;
                }

                /**
                 * Gets the value of the serija property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getSerija() {
                    return serija;
                }

                /**
                 * Sets the value of the serija property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setSerija(String value) {
                    this.serija = value;
                }

                /**
                 * Gets the value of the proizvodjac property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getProizvodjac() {
                    return proizvodjac;
                }

                /**
                 * Sets the value of the proizvodjac property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setProizvodjac(String value) {
                    this.proizvodjac = value;
                }

                /**
                 * Gets the value of the nezeljenaReakcija property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getNezeljenaReakcija() {
                    return nezeljenaReakcija;
                }

                /**
                 * Sets the value of the nezeljenaReakcija property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setNezeljenaReakcija(String value) {
                    this.nezeljenaReakcija = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="drzavljanstvo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="srpsko"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="jmbg" type="{http://www.akatsuki.org/tipovi}TJmbg"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="strano"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="broj_pasosa" type="{http://www.akatsuki.org/tipovi}TBrojPasosa"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="puno_ime"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="pol" type="{http://www.akatsuki.org/tipovi}TPol"/&gt;
     *         &lt;element name="rodjenje"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="prebivaliste"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="adresa"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="mesto_stanovanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fiksni_telefon" type="{http://www.akatsuki.org/tipovi}TFiksniTelefon"/&gt;
     *         &lt;element name="mobilni_telefon" type="{http://www.akatsuki.org/tipovi}TTelefon"/&gt;
     *         &lt;element name="imejl" type="{http://www.akatsuki.org/tipovi}TEmail"/&gt;
     *         &lt;element name="radni_status"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="zaposlen"/&gt;
     *               &lt;enumeration value="nezaposlen"/&gt;
     *               &lt;enumeration value="penzioner"/&gt;
     *               &lt;enumeration value="ucenik"/&gt;
     *               &lt;enumeration value="student"/&gt;
     *               &lt;enumeration value="dete"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="zanimanje"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="zdravstvena_zastita"/&gt;
     *               &lt;enumeration value="socijalna_zastita"/&gt;
     *               &lt;enumeration value="prosveta"/&gt;
     *               &lt;enumeration value="mup"/&gt;
     *               &lt;enumeration value="vojska_rs"/&gt;
     *               &lt;enumeration value="drugo"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="socijalna_zastita"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="sediste"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="izjava_saglasnosti"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="saglasnost" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="naziv_leka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="datum_popunjavanja" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "drzavljanstvo",
            "punoIme",
            "pol",
            "rodjenje",
            "prebivaliste",
            "fiksniTelefon",
            "mobilniTelefon",
            "imejl",
            "radniStatus",
            "zanimanje",
            "socijalnaZastita",
            "izjavaSaglasnosti"
    })
    public static class Pacijent {

        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected Drzavljanstvo drzavljanstvo;
        @XmlElement(name = "puno_ime", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected PunoIme punoIme;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        @XmlSchemaType(name = "string")
        protected TPol pol;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected Rodjenje rodjenje;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected Prebivaliste prebivaliste;
        @XmlElement(name = "fiksni_telefon", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected String fiksniTelefon;
        @XmlElement(name = "mobilni_telefon", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected String mobilniTelefon;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected String imejl;
        @XmlElement(name = "radni_status", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected String radniStatus;
        @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected String zanimanje;
        @XmlElement(name = "socijalna_zastita", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected SocijalnaZastita socijalnaZastita;
        @XmlElement(name = "izjava_saglasnosti", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
        protected IzjavaSaglasnosti izjavaSaglasnosti;
        @XmlAttribute(name = "datum_popunjavanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPopunjavanja;

        /**
         * Gets the value of the drzavljanstvo property.
         *
         * @return possible object is
         * {@link Drzavljanstvo }
         */
        public Drzavljanstvo getDrzavljanstvo() {
            return drzavljanstvo;
        }

        /**
         * Sets the value of the drzavljanstvo property.
         *
         * @param value allowed object is
         *              {@link Drzavljanstvo }
         */
        public void setDrzavljanstvo(Drzavljanstvo value) {
            this.drzavljanstvo = value;
        }

        /**
         * Gets the value of the punoIme property.
         *
         * @return possible object is
         * {@link PunoIme }
         */
        public PunoIme getPunoIme() {
            return punoIme;
        }

        /**
         * Sets the value of the punoIme property.
         *
         * @param value allowed object is
         *              {@link PunoIme }
         */
        public void setPunoIme(PunoIme value) {
            this.punoIme = value;
        }

        /**
         * Gets the value of the pol property.
         *
         * @return possible object is
         * {@link TPol }
         */
        public TPol getPol() {
            return pol;
        }

        /**
         * Sets the value of the pol property.
         *
         * @param value allowed object is
         *              {@link TPol }
         */
        public void setPol(TPol value) {
            this.pol = value;
        }

        /**
         * Gets the value of the rodjenje property.
         *
         * @return possible object is
         * {@link Rodjenje }
         */
        public Rodjenje getRodjenje() {
            return rodjenje;
        }

        /**
         * Sets the value of the rodjenje property.
         *
         * @param value allowed object is
         *              {@link Rodjenje }
         */
        public void setRodjenje(Rodjenje value) {
            this.rodjenje = value;
        }

        /**
         * Gets the value of the prebivaliste property.
         *
         * @return possible object is
         * {@link Prebivaliste }
         */
        public Prebivaliste getPrebivaliste() {
            return prebivaliste;
        }

        /**
         * Sets the value of the prebivaliste property.
         *
         * @param value allowed object is
         *              {@link Prebivaliste }
         */
        public void setPrebivaliste(Prebivaliste value) {
            this.prebivaliste = value;
        }

        /**
         * Gets the value of the fiksniTelefon property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getFiksniTelefon() {
            return fiksniTelefon;
        }

        /**
         * Sets the value of the fiksniTelefon property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setFiksniTelefon(String value) {
            this.fiksniTelefon = value;
        }

        /**
         * Gets the value of the mobilniTelefon property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMobilniTelefon() {
            return mobilniTelefon;
        }

        /**
         * Sets the value of the mobilniTelefon property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMobilniTelefon(String value) {
            this.mobilniTelefon = value;
        }

        /**
         * Gets the value of the imejl property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getImejl() {
            return imejl;
        }

        /**
         * Sets the value of the imejl property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setImejl(String value) {
            this.imejl = value;
        }

        /**
         * Gets the value of the radniStatus property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getRadniStatus() {
            return radniStatus;
        }

        /**
         * Sets the value of the radniStatus property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setRadniStatus(String value) {
            this.radniStatus = value;
        }

        /**
         * Gets the value of the zanimanje property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getZanimanje() {
            return zanimanje;
        }

        /**
         * Sets the value of the zanimanje property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setZanimanje(String value) {
            this.zanimanje = value;
        }

        /**
         * Gets the value of the socijalnaZastita property.
         *
         * @return possible object is
         * {@link SocijalnaZastita }
         */
        public SocijalnaZastita getSocijalnaZastita() {
            return socijalnaZastita;
        }

        /**
         * Sets the value of the socijalnaZastita property.
         *
         * @param value allowed object is
         *              {@link SocijalnaZastita }
         */
        public void setSocijalnaZastita(SocijalnaZastita value) {
            this.socijalnaZastita = value;
        }

        /**
         * Gets the value of the izjavaSaglasnosti property.
         *
         * @return possible object is
         * {@link IzjavaSaglasnosti }
         */
        public IzjavaSaglasnosti getIzjavaSaglasnosti() {
            return izjavaSaglasnosti;
        }

        /**
         * Sets the value of the izjavaSaglasnosti property.
         *
         * @param value allowed object is
         *              {@link IzjavaSaglasnosti }
         */
        public void setIzjavaSaglasnosti(IzjavaSaglasnosti value) {
            this.izjavaSaglasnosti = value;
        }

        /**
         * Gets the value of the datumPopunjavanja property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getDatumPopunjavanja() {
            return datumPopunjavanja;
        }

        /**
         * Sets the value of the datumPopunjavanja property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setDatumPopunjavanja(XMLGregorianCalendar value) {
            this.datumPopunjavanja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="srpsko"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="jmbg" type="{http://www.akatsuki.org/tipovi}TJmbg"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="strano"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="broj_pasosa" type="{http://www.akatsuki.org/tipovi}TBrojPasosa"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "srpsko",
                "strano"
        })
        public static class Drzavljanstvo {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju")
            protected Srpsko srpsko;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju")
            protected Strano strano;

            /**
             * Gets the value of the srpsko property.
             *
             * @return possible object is
             * {@link Srpsko }
             */
            public Srpsko getSrpsko() {
                return srpsko;
            }

            /**
             * Sets the value of the srpsko property.
             *
             * @param value allowed object is
             *              {@link Srpsko }
             */
            public void setSrpsko(Srpsko value) {
                this.srpsko = value;
            }

            /**
             * Gets the value of the strano property.
             *
             * @return possible object is
             * {@link Strano }
             */
            public Strano getStrano() {
                return strano;
            }

            /**
             * Sets the value of the strano property.
             *
             * @param value allowed object is
             *              {@link Strano }
             */
            public void setStrano(Strano value) {
                this.strano = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="jmbg" type="{http://www.akatsuki.org/tipovi}TJmbg"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "jmbg"
            })
            public static class Srpsko {

                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String jmbg;

                /**
                 * Gets the value of the jmbg property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getJmbg() {
                    return jmbg;
                }

                /**
                 * Sets the value of the jmbg property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setJmbg(String value) {
                    this.jmbg = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="broj_pasosa" type="{http://www.akatsuki.org/tipovi}TBrojPasosa"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "naziv",
                    "brojPasosa"
            })
            public static class Strano {

                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String naziv;
                @XmlElement(name = "broj_pasosa", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String brojPasosa;

                /**
                 * Gets the value of the naziv property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getNaziv() {
                    return naziv;
                }

                /**
                 * Sets the value of the naziv property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setNaziv(String value) {
                    this.naziv = value;
                }

                /**
                 * Gets the value of the brojPasosa property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getBrojPasosa() {
                    return brojPasosa;
                }

                /**
                 * Sets the value of the brojPasosa property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setBrojPasosa(String value) {
                    this.brojPasosa = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="saglasnost" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="naziv_leka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "saglasnost",
                "nazivLeka"
        })
        public static class IzjavaSaglasnosti {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju")
            protected boolean saglasnost;
            @XmlElement(name = "naziv_leka", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String nazivLeka;

            /**
             * Gets the value of the saglasnost property.
             */
            public boolean isSaglasnost() {
                return saglasnost;
            }

            /**
             * Sets the value of the saglasnost property.
             */
            public void setSaglasnost(boolean value) {
                this.saglasnost = value;
            }

            /**
             * Gets the value of the nazivLeka property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getNazivLeka() {
                return nazivLeka;
            }

            /**
             * Sets the value of the nazivLeka property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setNazivLeka(String value) {
                this.nazivLeka = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="adresa"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="mesto_stanovanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "adresa",
                "mestoStanovanja",
                "opstina"
        })
        public static class Prebivaliste {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected Adresa adresa;
            @XmlElement(name = "mesto_stanovanja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String mestoStanovanja;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String opstina;

            /**
             * Gets the value of the adresa property.
             *
             * @return possible object is
             * {@link Adresa }
             */
            public Adresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             *
             * @param value allowed object is
             *              {@link Adresa }
             */
            public void setAdresa(Adresa value) {
                this.adresa = value;
            }

            /**
             * Gets the value of the mestoStanovanja property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getMestoStanovanja() {
                return mestoStanovanja;
            }

            /**
             * Sets the value of the mestoStanovanja property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setMestoStanovanja(String value) {
                this.mestoStanovanja = value;
            }

            /**
             * Gets the value of the opstina property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getOpstina() {
                return opstina;
            }

            /**
             * Sets the value of the opstina property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setOpstina(String value) {
                this.opstina = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "ulica",
                    "broj"
            })
            public static class Adresa {

                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String ulica;
                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected BigInteger broj;

                /**
                 * Gets the value of the ulica property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getUlica() {
                    return ulica;
                }

                /**
                 * Sets the value of the ulica property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setUlica(String value) {
                    this.ulica = value;
                }

                /**
                 * Gets the value of the broj property.
                 *
                 * @return possible object is
                 * {@link BigInteger }
                 */
                public BigInteger getBroj() {
                    return broj;
                }

                /**
                 * Sets the value of the broj property.
                 *
                 * @param value allowed object is
                 *              {@link BigInteger }
                 */
                public void setBroj(BigInteger value) {
                    this.broj = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ime_roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "prezime",
                "ime",
                "imeRoditelja"
        })
        public static class PunoIme {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String prezime;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String ime;
            @XmlElement(name = "ime_roditelja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String imeRoditelja;

            /**
             * Gets the value of the prezime property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the ime property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the imeRoditelja property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getImeRoditelja() {
                return imeRoditelja;
            }

            /**
             * Sets the value of the imeRoditelja property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setImeRoditelja(String value) {
                this.imeRoditelja = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="mesto_rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "datumRodjenja",
                "mestoRodjenja"
        })
        public static class Rodjenje {

            @XmlElement(name = "datum_rodjenja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumRodjenja;
            @XmlElement(name = "mesto_rodjenja", namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected String mestoRodjenja;

            /**
             * Gets the value of the datumRodjenja property.
             *
             * @return possible object is
             * {@link XMLGregorianCalendar }
             */
            public XMLGregorianCalendar getDatumRodjenja() {
                return datumRodjenja;
            }

            /**
             * Sets the value of the datumRodjenja property.
             *
             * @param value allowed object is
             *              {@link XMLGregorianCalendar }
             */
            public void setDatumRodjenja(XMLGregorianCalendar value) {
                this.datumRodjenja = value;
            }

            /**
             * Gets the value of the mestoRodjenja property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getMestoRodjenja() {
                return mestoRodjenja;
            }

            /**
             * Sets the value of the mestoRodjenja property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setMestoRodjenja(String value) {
                this.mestoRodjenja = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="sediste"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "korisnik",
                "sediste"
        })
        public static class SocijalnaZastita {

            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju")
            protected boolean korisnik;
            @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
            protected Sediste sediste;

            /**
             * Gets the value of the korisnik property.
             */
            public boolean isKorisnik() {
                return korisnik;
            }

            /**
             * Sets the value of the korisnik property.
             */
            public void setKorisnik(boolean value) {
                this.korisnik = value;
            }

            /**
             * Gets the value of the sediste property.
             *
             * @return possible object is
             * {@link Sediste }
             */
            public Sediste getSediste() {
                return sediste;
            }

            /**
             * Sets the value of the sediste property.
             *
             * @param value allowed object is
             *              {@link Sediste }
             */
            public void setSediste(Sediste value) {
                this.sediste = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "naziv",
                    "opstina"
            })
            public static class Sediste {

                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String naziv;
                @XmlElement(namespace = "http://www.akatsuki.org/saglasnost_za_imunizaciju", required = true)
                protected String opstina;

                /**
                 * Gets the value of the naziv property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getNaziv() {
                    return naziv;
                }

                /**
                 * Sets the value of the naziv property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setNaziv(String value) {
                    this.naziv = value;
                }

                /**
                 * Gets the value of the opstina property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getOpstina() {
                    return opstina;
                }

                /**
                 * Sets the value of the opstina property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setOpstina(String value) {
                    this.opstina = value;
                }

            }

        }

    }

}
