//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.14 at 09:29:21 AM CET 
//


package akatsuki.immunizationsystem.model.documents;

import akatsuki.immunizationsystem.model.types.TPodnosilacZahteva;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podnosilac" type="{http://www.akatsuki.org/tipovi}TPodnosilacZahteva"/&gt;
 *         &lt;element name="razlog_podnosenja_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="mesto" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "podnosilac",
        "razlogPodnosenjaZahteva"
})
@XmlRootElement(name = "zahtev_za_sertifikat", namespace = "http://www.akatsuki.org/zahtev_za_sertifikat")
public class ZahtevZaSertifikat {

    @XmlElement(namespace = "http://www.akatsuki.org/zahtev_za_sertifikat", required = true)
    protected TPodnosilacZahteva podnosilac;
    @XmlElement(name = "razlog_podnosenja_zahteva", namespace = "http://www.akatsuki.org/zahtev_za_sertifikat", required = true)
    protected String razlogPodnosenjaZahteva;
    @XmlAttribute(name = "datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "mesto", required = true)
    protected String mesto;

    /**
     * Gets the value of the podnosilac property.
     *
     * @return possible object is
     * {@link TPodnosilacZahteva }
     */
    public TPodnosilacZahteva getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     *
     * @param value allowed object is
     *              {@link TPodnosilacZahteva }
     */
    public void setPodnosilac(TPodnosilacZahteva value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the razlogPodnosenjaZahteva property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRazlogPodnosenjaZahteva() {
        return razlogPodnosenjaZahteva;
    }

    /**
     * Sets the value of the razlogPodnosenjaZahteva property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRazlogPodnosenjaZahteva(String value) {
        this.razlogPodnosenjaZahteva = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the mesto property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

}
